feat : add jump, damaged state & damaged animation
developerasun/myCodeBox-unity pull request #90
Opened 2022-03-11 11:09 UTC by jshhhhh

* jump, damaged 상태 추가 및 코드 정리
* 적에게 데미지를 입으면 빨간색으로 깜빡이는 간단한 애니메이션 추가

![데미지 입는 애니메이션](https://user-images.githubusercontent.com/86046319/157855891-35bf67c0-6ee0-4dd5-86d7-3a7616582181.jpg)

2022-03-11 12:29 UTC, developerasun requested changes

2022-03-11 12:29 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +1. w,s,space키로 좌우 이동 및 점프 기능
w,s 로 좌우 이동이에요? 앞 뒤가 아니구??

2022-03-11 12:29 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
>      public AudioClip jumpSound;
AudioManager 변수들 앞에 Prefix로 S붙이는 걸로 네이밍 통일하는 건 어떄유

## before 
- jumpSound
- demageSound 

## after 
- SJump
- SDemage

2022-03-11 12:29 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +        animator.SetInteger("animationState", 1);
이거 사운드나 애니메이션 업데이트 할 때 일일히 반복해서 적는 거보다 함수 하나 만들어서 쓰는 건 어떄유? 예를 들면

```c# 
void AnimationSetter(string _name, T _condition) {
   // 조건 T에 따라 animator.SetBool 또는  animator.SetInteger 실행
}

```

2022-03-11 12:29 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
>          tagOfFooting = returnTagOfFooting();
이 태그는 유니티 에디터 inspector탭에서 설정 안되는 태그들인거에유?

2022-03-11 12:29 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +        if (tagOfFooting == FLOOR)
이 부분 CompareTag 메소드 말고 스트링 값으로 비교하는 이유가 있나유?

2022-03-12 05:56 UTC, jshhhhh commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +1. w,s,space키로 좌우 이동 및 점프 기능
주석 실수😅 수정하겠음

2022-03-12 05:57 UTC, jshhhhh commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
>      public AudioClip jumpSound;
어떻게 달든 상관은 없지만 이것도 좋은 방법 같음. 수정하겠음

2022-03-12 06:06 UTC, jshhhhh commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +        animator.SetInteger("animationState", 1);
이게 [제네릭](https://github.com/jshhhhh/Unity-2D-Roguelike/issues/4) 문법인가? 이해가 잘 안 됐는데 추가로 설명해줄 수 있음?

2022-03-12 06:30 UTC, jshhhhh commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
>          tagOfFooting = returnTagOfFooting();
OnCollisionEnter로 Box Collider에 닿는 모든 태그를 가져오는 게 아니고, 플레이어 발에 닿는 태그만 가져오려면 좀 복잡하게 만들 수밖에 없었음
여기서 가져온 태그(tagOfFooting)가 floor인지 아닌지로 착지했는지 아닌지를 판단하는 로직
더 좋은 방법 있으면 알려줘
```csharp
...
private string returnTagOfFooting()
{
    //평평한 바닥과의 최소 높이(에디터 상에서 노가다로 대략적인 수치 구함)
    //내리막에서나 오르막 발판에서의 수치는 아직 불확실
    float minHeightFromHit = 0.08f;
    string _tagOfFooting;

    //Ray를 시각적으로 표시
    Debug.DrawRay(transform.position, -transform.up * minHeightFromHit, Color.red);

    RaycastHit hit;

    //Ray를 바닥 방향(-transform.up)으로 minHeightFromHit만큼 짧게 쏘아서 닿는 오브젝트의 태그 추출
    if (Physics.Raycast(transform.position, -transform.up, out hit, minHeightFromHit))
        _tagOfFooting = hit.collider.tag;
    else
        _tagOfFooting = null;

    return _tagOfFooting;
}
...
```

```csharp
...
void UpdateMove()
{
    animator.SetInteger("animationState", 1);

    canJump = true;

    playerMove();

    //상태 전환 조건
    //바닥을 딛고 있지 않으면 Jump 상태로(낙하 포함)
    if (tagOfFooting != FLOOR)
        _state = playerState.Jump;

    if (Input.GetKeyDown(KeyCode.Space) && canJump)
        playerJump();
}
....
```

2022-03-12 06:51 UTC, jshhhhh commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +        if (tagOfFooting == FLOOR)
tagOfFooting이 string이라 string으로 비교한 것뿐인데👀

잘 몰라서 CompareTag 함수 찾아보니까
```csharp
void OnTriggerEnter(Collider other)
{
    if (other.gameObject.CompareTag("Player"))
    {
        Destroy(other.gameObject);
    }
}
```
예시처럼 특정 오브젝트의 태그를 비교하는 것 같은데, 그러려면 위의 returnTagOfFooting에서 발에 접촉하는 태그 말고 오브젝트를 반환하도록 함수를 수정해야 할 것 같음

참고 : [Unity Documentation : Component.CompareTag](https://docs.unity3d.com/kr/current/ScriptReference/Component.CompareTag.html)

2022-03-12 06:59 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +        animator.SetInteger("animationState", 1);
이거 방금 제네릭 찾아서 간단하게 짜봤는데 이렇게 하면 일일히 SetBool, SetInteger 안 부르고 그냥 파라미터 값만 넣어주면 되유

```cs
    void AnimationSetter<T>(string _name, T _condition) {
   // 조건 T에 따라 animator.SetBool 또는  animator.SetInteger 실행
        if (typeof (_condition) == typeof(bool)) {
            animator.SetBool(_name, _condition);
        }
        if (typeof (_condition) == typeof(int)) {
            animator.SetInteger(_name, _condition);
        }
    }
```

2022-03-12 07:03 UTC, developerasun commented on miniProjects/meowRun/unity/Assets/Scripts/Player.cs
> +        if (tagOfFooting == FLOOR)
보통 스크립트에서 CompareTag 많이 쓰고 tag는 유니티 에디터 inspector 탭에서 바로 설정할 수 있잖음??  그게 훨씬 간단할텐디

2022-03-12 08:37 UTC, developerasun approved these changes

2022-03-12 08:37 UTC, merged